### ISSUE TITLE
This buildpack's "web" process overrides the one in Procfile

### ISSUE THREAD

**Issue by effulgentsia** [paketo-buildpacks/php-start#124]
If I add a `Procfile` at the root of my app with the following:
```
web: echo "hello"
```

Then I'd expect that to take priority over the "web" process added by the php-start buildpack. However, when I run `pack build`, the paketo-buildpacks/procfile buildpack runs before the paketo-buildpacks/php-start buildpack, and so the resulting image's web process is the one set by php-start rather the one I specified in my Procfile.

Is my expectation correct, or is it by design that php-start override procfile?

In the meantime, I can work around this by using a different name than "web" in my Procfile and then making that other name the default process. Or, is there a better workaround available: for example, is there something I can do to change the order in which build packs run so that paketo-buildpacks/procfile runs after paketo-buildpacks/php-start?

**Comment by effulgentsia** [comment]
Some more info. If in my project.toml I have:
```
group = [
  {uri = "paketo-buildpacks/nodejs"},
  {uri = "paketo-buildpacks/php"}
]
```
That's when the builder runs procfile before php-start, because procfile is a component of paketo-buildpacks/nodejs as well as being a component of paketo-buildpacks/php. If I only have:
```
group = [
  {uri = "paketo-buildpacks/php"}
]
```

Then procfile comes after php-start as expected.

If I switch the order to:
```
group = [
  {uri = "paketo-buildpacks/php"},
  {uri = "paketo-buildpacks/nodejs"}
]

```

That doesn't help my use-case, because even though it makes procfile run after php-start, then node-start runs after procfile and overrides it.

I also tried:
```
group = [
  {uri = "paketo-buildpacks/php"},
  {uri = "paketo-buildpacks/nodejs"},
  {uri = "paketo-buildpacks/procfile"}
]
```

But that doesn't solve it, because the order in which procfile runs is determined by the first place that brings it in rather than the last.

**Comment by ryanmoran** [comment]
We didn't really design the top-level buildpacks to cooperate to achieve the outcome you seem to be trying for. They are mostly designed to be used on their own. Can I ask what parts of the Node.js buildpack you are using in your build process and what the expected build process should look like?
